export const STORAGE_KEYS = {
  AUTH_TOKEN: 'resumai_auth_token',
  AUTH_USER: 'resumai_auth_user',
  ACTIVE_RESUME: 'resumai_active_resume',
  ACTIVE_TEMPLATE: 'resumai_active_template',
};

export const ROLES = {
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
};

export const RESUME_TEMPLATES = {
  MODERN: 'modern',
  CLASSIC: 'classic',
  PROFESSIONAL: 'professional',
  MINIMAL: 'minimal',
  CREATIVE: 'creative',
  DEVELOPER: 'developer',
  CORPORATE: 'corporate',
  EXECUTIVE: 'executive',
  ATS_FRIENDLY: 'ats-friendly',
  TWO_COLUMN: 'two-column',
};

export const TEMPLATE_OPTIONS = [
  {
    id: RESUME_TEMPLATES.MODERN,
    name: 'Modern Tech',
    description: 'Clean, contemporary layout tailored for software engineers & tech professionals.',
    badge: 'Popular',
    accentColor: '#026bc9',
    category: 'Standard',
  },
  {
    id: RESUME_TEMPLATES.CLASSIC,
    name: 'Classic Traditional',
    description: 'Timeless serif typography with balanced margins. Ideal for law, finance, and academia.',
    badge: 'Traditional',
    accentColor: '#1e293b',
    category: 'Standard',
  },
  {
    id: RESUME_TEMPLATES.PROFESSIONAL,
    name: 'Professional Corporate',
    description: 'Structured grid with clear horizontal dividers and strong hierarchical headings.',
    badge: 'Corporate',
    accentColor: '#0f766e',
    category: 'Corporate',
  },
  {
    id: RESUME_TEMPLATES.MINIMAL,
    name: 'Minimalist Clean',
    description: 'Ultra clean, distraction-free layout emphasizing key achievements and readable metrics.',
    badge: 'Minimal',
    accentColor: '#334155',
    category: 'Standard',
  },
  {
    id: RESUME_TEMPLATES.CREATIVE,
    name: 'Creative Portfolio',
    description: 'Dynamic header with bold branding and stylized skill badges for designers & frontend devs.',
    badge: 'Creative',
    accentColor: '#7c3aed',
    category: 'Creative',
  },
  {
    id: RESUME_TEMPLATES.DEVELOPER,
    name: 'Developer Monospace',
    description: 'Code-inspired accents, git icons, tech chips, and monospace highlights for software engineers.',
    badge: 'Tech',
    accentColor: '#059669',
    category: 'Tech',
  },
  {
    id: RESUME_TEMPLATES.CORPORATE,
    name: 'Corporate Navy',
    description: 'Executive navy header with clean sections tailored for corporate and enterprise roles.',
    badge: 'Enterprise',
    accentColor: '#1e3a8a',
    category: 'Corporate',
  },
  {
    id: RESUME_TEMPLATES.EXECUTIVE,
    name: 'Executive Leadership',
    description: 'Sophisticated slate headers and highlighted career milestones for directors and managers.',
    badge: 'Leadership',
    accentColor: '#475569',
    category: 'Executive',
  },
  {
    id: RESUME_TEMPLATES.ATS_FRIENDLY,
    name: 'ATS Optimized',
    description: 'High-parseability single column layout engineered specifically to pass recruiter robot filters.',
    badge: 'ATS 100%',
    accentColor: '#2563eb',
    category: 'ATS',
  },
  {
    id: RESUME_TEMPLATES.TWO_COLUMN,
    name: 'Two Column Compact',
    description: 'Dual-column efficiency placing contact and skills on the left with experience on the right.',
    badge: 'Compact',
    accentColor: '#0891b2',
    category: 'Standard',
  },
];

export const RESUME_TEMPLATES_LIST = TEMPLATE_OPTIONS;

export const INITIAL_RESUME_STATE = {
  title: 'Senior Software Engineer Resume',
  template: RESUME_TEMPLATES.MODERN,
  personalInfo: {
    fullName: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    phone: '+1 (555) 019-2834',
    location: 'San Francisco, CA',
    linkedin: 'linkedin.com/in/alexmorgan',
    github: 'github.com/alexmorgan',
  },
  summary: 'Results-driven Full Stack Software Engineer with 5+ years of experience building high-scale distributed web applications using React, Java, Spring Boot, and cloud architectures. Proven track record in optimizing system throughput, leading agile engineering teams, and shipping production microservices.',
  careerObjective: 'Passionate senior technologist dedicated to architecting scalable cloud platforms, driving developer velocity, and delivering mission-critical web applications.',
  education: [
    {
      id: 'edu-1',
      institution: 'University of California, Berkeley',
      degree: 'B.S. in Computer Science',
      fieldOfStudy: 'Computer Systems & Software Engineering',
      startYear: '2016',
      endYear: '2020',
      description: 'Graduated Magna Cum Laude (GPA 3.9/4.0). Coursework: Distributed Systems, Algorithms, Database Management.',
    },
  ],
  experience: [
    {
      id: 'exp-1',
      company: 'TechFlow Systems',
      role: 'Senior Full Stack Engineer',
      startDate: 'Jan 2022',
      endDate: 'Present',
      current: true,
      description: '• Architected core SaaS microservices with Spring Boot and React, scaling platform to 350k+ daily active users.\n• Optimized database query plans and Redis cache invalidation, reducing P99 latency by 45%.\n• Spearheaded automated CI/CD pipeline modernization with Docker and GitHub Actions, cutting release cycles in half.',
    },
    {
      id: 'exp-2',
      company: 'NovaCore Solutions',
      role: 'Software Developer',
      startDate: 'Jul 2020',
      endDate: 'Dec 2021',
      current: false,
      description: '• Developed responsive component design systems in React and Tailwind CSS for multi-tenant customer dashboard.\n• Implemented secure JWT authentication and role-based access control across 20+ REST microservice endpoints.\n• Maintained 90%+ code coverage with JUnit, Mockito, and Jest automated test suites.',
    },
  ],
  internships: [
    {
      id: 'intern-1',
      company: 'Apex Data Labs',
      role: 'Software Engineering Intern',
      startDate: 'Jun 2019',
      endDate: 'Aug 2019',
      current: false,
      description: '• Built automated ETL data ingestion scripts in Python and SQL for analytics reporting pipelines.',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'CloudScale Real-Time Health Dashboard',
      technologies: 'React, Spring Boot, WebSocket, Docker, MongoDB',
      description: 'Engineered a high-throughput microservices health monitoring dashboard with live metric charts and alert notifications.',
      link: 'https://github.com/alexmorgan/cloudscale',
    },
    {
      id: 'proj-2',
      title: 'AI Smart Resume & Job Alignment Engine',
      technologies: 'React, Node.js, Gemini API, Tailwind CSS',
      description: 'Created an intelligent semantic keyword benchmarking system parsing resumes and calculating ATS compatibility scores.',
      link: 'https://github.com/alexmorgan/resumai',
    },
  ],
  skills: [
    'React.js',
    'JavaScript (ES6+)',
    'TypeScript',
    'Java',
    'Spring Boot',
    'MongoDB',
    'PostgreSQL',
    'REST APIs',
    'Docker',
    'Tailwind CSS',
    'Git & GitHub',
    'Microservices Architecture',
    'CI/CD Pipelines',
    'AWS Cloud',
  ],
  technicalSkills: [
    'Frontend: React, TypeScript, Tailwind CSS, Next.js, Redux Toolkit',
    'Backend: Java 17, Spring Boot, Spring Data, Node.js, Express',
    'Databases: MongoDB, PostgreSQL, Redis, MySQL',
    'DevOps: Docker, Kubernetes, AWS (S3, EC2), CI/CD, Git',
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      issueDate: '2023',
      credentialUrl: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-2',
      name: 'Oracle Certified Professional: Java SE 17 Developer',
      issuer: 'Oracle Corporation',
      issueDate: '2022',
      credentialUrl: 'https://oracle.com/certview',
    },
  ],
  achievements: [
    'Awarded Employee of the Year (2023) at TechFlow Systems for driving cloud cost reduction by 30%.',
    '1st Place Winner at Bay Area Hackathon 2021 among 80+ participating engineering teams.',
  ],
  languages: [
    'English (Native / Bilingual)',
    'Spanish (Professional Working Proficiency)',
  ],
  hobbies: [
    'Open Source Contribution',
    'Tech Blogging & Mentoring',
    'Competitive Chess',
  ],
  customSections: [],
};
